title: Corp-i1's Pages
description: Documentation for my projects as some other stuff.
theme: just-the-docs
url: https://Corp-i1.github.io/GitHub-Pages
aux_links: # remove if you don't want this link to appear on your pages
    Template Repository: https://Corp-i1.github.io/GitHub-Pages
