title: Corp-i1's Pages
description: Documentation for my projects as some other stuff.
theme: just-the-docs
color_scheme: dark
url: https://Corp-i1.github.io/Github-Pages/
ga_tracking: G-6E1Z07F6MZ
ga_tracking_anonymize_ip: true
favicon_ico: "/assets/images/Win-Labs_Icon.jpg"